services:
  db:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    env_file:
      - .env.postgres
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: gleidsoncosta/jade-admin-api:latest
    ports:
      - "8000:8000"
    depends_on:
      - cache
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env

volumes:
  db:
  cache:
